apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-lvm-storageclass
provisioner: lvmplugin.csi.alibabacloud.com
parameters:
  vgName: vgdata
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
