apiVersion: v1
kind: Service
metadata:
  name: nwpu-hdfs
spec:
  type: NodePort
  selector:
    name: nwpu-namenode
  ports:
    - name: rpc
      port: 9000
      targetPort: 9000
    - name: http
      port: 50070
      targetPort: 50070
      nodePort: 32007
